### PR TITLE
Trees 🌳 

### PR DESCRIPTION
**Pull request by amitsuthar69**
## Title :

TREES 🌳 

## Issue no :

N/A

## Description

Really ? 

## Checkboxes

- [x] This pr works

### CODE REVIEW

**Review by Rishabh672003 — APPROVED** [review]
LGTM

**Comment by Rishabh672003** [comment]
@amitsuthar69 set up gpg for your git, then your commits will be verified

**Comment by amitsuthar69** [comment]
> @amitsuthar69 set up gpg for your git, then your commits will be verified

I don't know what's that

**Comment by Rishabh672003** [comment]
@amitsuthar69 
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

**Pull request merged**
